apiVersion: v1
kind: Service
metadata:
  name: tc-website-lb
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO:  this value should be by env property .
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {CERTIFICATE_ARN}
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: tc-website
  ports:
    - name: https
      port: 443
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc-website
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tc-website
  template:
    metadata:
      labels:
        app: tc-website
    spec:
      containers:
        - name: tc-website
          imagePullPolicy: Always
          image: 082655277789.dkr.ecr.us-east-2.amazonaws.com/tc-website-temp-repository-{IMAGE}:latest
          ports:
            - containerPort: 3000
          env:
            - name: HELP_CENTER_PASSWORD
              value: "{HELP_CENTER_PASSWORD}"
            - name: HELP_CENTER_SECRET
              value: "{HELP_CENTER_SECRET}"